### PR TITLE
feat(indianapolis,kaffiene): add images / summary

### PR DESCRIPTION
**Pull request by lewxdev**

### CODE REVIEW

**Comment by lewxdev** [comment]
@pqvst not sure why these latest changes weren't deployed. was it because of the `updated` attribute? should it be removed?

**Comment by pqvst** [comment]
Ah, sorry, it doesn't auto-deploy at the moment. It should be live now!

**Comment by lewxdev** [comment]
Thanks! Though it seems like [Moar Tea](https://cafeandcowork.com/indianapolis/moar-tea/) is still missing the updated images 🤔

**Comment by pqvst** [comment]
I purged the cloudflare cache and it seems to be working now (you might need to clear your local cache as well)

**Comment by lewxdev** [comment]
I see it now, thanks!

**Pull request merged**
